---
title: "Code"
---

```{r}
library(tidyverse)
library(viridis)
library(p8105.datasets)

library(plotly)
```


```{r}
set.seed(1)

data(ny_noaa)

tidy_noaa = 
  ny_noaa %>%
  separate(date, into = c("year", "month", "day"), sep = "-") %>% #add year, month, and day
  mutate(prcp = prcp/10, 
         tmax = as.numeric(tmax)/10,
         tmin = as.numeric(tmin)/10) %>% #convert values of prcp to mm and temp to ºC
  sample_n(5000) #focus on randomly selected 1000 samples
```

### Plotly boxplot

```{r}
tidy_noaa %>%
  select(-(day:snwd), -tmin) %>%
  filter(month %in% c("01", "07") & !is.na(tmax)) %>% #get Jan and July data, and remove any missing value for tmax
  group_by(year, month, id) %>%
  summarize(mean_tmax = mean(tmax)) %>%
  plot_ly(x = ~ month, y = ~mean_tmax, color = ~ year, type = "box") %>%
  layout(boxmode = "group",
         title = "Average Max Temperature In Each Station from 1981 to 2010 (January VS. July)",
         yaxis = list(title = "Mean Max Temperature (ºC)")) #create two-panel plots by month
```

### Plotly scatterplot

```{r}
tidy_noaa %>%
  filter(!is.na(tmax) & !is.na(tmin),
         month %in% c("01", "02", "03", "04", "05", "06")) %>%
  plot_ly(x = ~ tmin, y = ~ tmax, type = "scatter", mode = "markers",
          alpha = 0.5,
          color = ~ month) %>%
  layout(xaxis = list(title = "Minimum temperature (ºC)"),
         yaxis = list(title = "Maximum temperature (ºC)")) #plot scatterplot showing tmax vs. tmin
```

### Plotly violinplot

```{r}
tidy_noaa %>%
  filter(snow > 0 & snow < 100) %>%
  plot_ly(x = ~ year, y = ~ snow, split = ~ year, type = "violin",
          box = list(visible = T),
          meanline = list(visible = T)) %>%
  layout(xaxis = list(title = "Year"),
         yaxis = list(title = "Snowfall (mm)")) #plot violin showing distribution
    
```

