---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly) #load libraries
```


```{r, tidy_data}
set.seed(1) #select same random samples each time

data(ny_noaa) #get data

tidy_noaa = 
  ny_noaa %>%
  separate(date, into = c("year", "month", "day"), sep = "-") %>% #add year, month, and day
  mutate(prcp = prcp/10, 
         tmax = as.numeric(tmax)/10,
         tmin = as.numeric(tmin)/10) %>% #convert values of prcp to mm and temp to ºC
  sample_n(5000) #focus on randomly selected 1000 samples
```



Column {data-width=500}
-----------------------------------------------------------------------

### Average Max Temperature In Each Station from 1981 to 2010 (January VS. July)

```{r, plot_1}
tidy_noaa %>%
  select(-(day:snwd), -tmin) %>%
  filter(month %in% c("01", "07") & !is.na(tmax)) %>% #get Jan and July data, and remove any missing value for tmax
  group_by(year, month, id) %>%
  summarize(mean_tmax = mean(tmax)) %>%
  plot_ly(x = ~ month, y = ~mean_tmax, color = ~ year, type = "box") %>%
  layout(boxmode = "group",
         yaxis = list(title = "Mean Max Temperature (ºC)")) #create boxplot by month
```

Column {data-width=500}
-----------------------------------------------------------------------

### tmax vs. tmin

```{r, plot_2}
tidy_noaa %>%
  filter(!is.na(tmax) & !is.na(tmin)) %>%
  plot_ly(x = ~ tmin, y = ~ tmax, type = "scatter", mode = "markers",
          alpha = 0.5,
          color = ~ month, colors = "Set3") %>%
  layout(xaxis = list(title = "Minimum temperature (ºC)"),
         yaxis = list(title = "Maximum temperature (ºC)")) #plot scatterplot showing tmax vs. tmin
```

### The Distribution of Snowfall Values from 0mm and 100mm by Year

```{r, plot_3}
tidy_noaa %>%
  filter(snow > 0 & snow < 100) %>%
  plot_ly(x = ~ year, y = ~ snow, split = ~ year, type = "violin",
          box = list(visible = T),
          meanline = list(visible = T)) %>%
  layout(xaxis = list(title = "Year"),
         yaxis = list(title = "Snowfall (mm)")) #plot violin showing distribution
```

